config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'posts#index', as: "home"

  get 'about' => 'pages#about', as: "about"
  post 'search' => 'posts#search', as: "search"
  get 'contacts' => 'pages#contacts', as: "contacts"
  get 'profile' => 'pages#curruserposts', as: "profile"
  get 'change_user_avatar' => 'pages#change_user_avatar', as: 'change_user_avatar'
  post 'change_user_avatar_method' => 'posts#change_user_avatar_method', as: 'change_user_avatar_method'

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_one_attached :image
  validates :title, presence: true, length: {minimum: 5}
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #http_basic_authenticate_with name: "admin", password: "adminrubyblog",
    #except: [:index, :show]
  before_action :authenticate_user!

  def create #called by submit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(commentValid)
    @comment.userName = current_user.email
    @comment.save

    redirect_to post_path(@post)
  end

  private def commentValid
    params.require(:comment).permit(:userName, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contacts

  end

  def about

  end

  def curruserposts
    @posts = Post.where(user_id: current_user.id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #http_basic_authenticate_with name: "admin", password: "adminrubyblog",
    #except: [:index, :show]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @topPosts = Array.new
    Post.all.each do |post|
      @topPosts.push(post)
    end

    n = @topPosts.length - 1
    n.times do |i|
      min_index = i
      for j in (i + 1)..n
        min_index = j if @topPosts[j].comments.count < @topPosts[min_index].comments.count
      end
      @topPosts[i], @topPosts[min_index] = @topPosts[min_index], @topPosts[i] if min_index != i
    end

    @topPosts.sort_by {|obj| obj.comments.count}
    @topPosts = @topPosts.last(3)

    @posts = Post.order(id: :desc)
  end

  def search
    
    @req = params["post"]["requeststring"]
    puts "!!!!!!!!!!!!!!!"
    puts @req
    puts "!!!!!!!!!!!!!!!"
    @posts = Array.new
    Post.all.each do |p|
      if p.title.nil? || p.body.nil?
        puts "err"

      elsif p.title.include? @req
        @posts.push(p)
      elsif p.body.include? @req
        @posts.push(p)
      end

    end

  end



  def new
    @post=Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @user = User.find(current_user.id)
    #render plain: params[:post].inspect
    @post = @user.posts.create(postValidate)
    @post.user_id = current_user.id

    if(@post.save)
      redirect_to @post #call show()
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])

    if(@post.update(postValidate))
      redirect_to @post #call show()
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.title = "deleted"
    @post.save
    #@post.destroy!
    if(@post.destroy)
      redirect_to posts_path #call show()
    else
      redirect_to @post
    end
  end

  


  def change_user_avatar_method
    current_user.image.attach imgValidate[:image]
    current_user.save

    redirect_to action: 'index'
  end


  private def postValidate
    params.require(:post).permit(:title,:body,:image)
  end

  private def imgValidate
    params.require(:avatar).permit(:image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'https://getbootstrap.com/docs/5.0/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css' %>

  </head>

  <body>
    
    <header class="p-3 mb-3 border-bottom">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
            <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
          </a>

          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><span class="nav-link px-2 link-secondary"><%= link_to "Main Page", home_path %></span></li>
            <li><span class="nav-link px-2 link-dark"><%= link_to "Create post", new_post_path %></span></li>
            <!--<li><span class="nav-link px-2 link-dark"><%= link_to "About", about_path %></span></li>
            #<li><span class="nav-link px-2 link-dark"><%= link_to "Contacts", contacts_path %></span></li>-->
          </ul>

          <% if current_page?(home_path) %>
            <%= form_for :post, url: search_path do |f| %>
              <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              
                <li><%= f.text_field :requeststring, :class=>"form-control" ,placeholder: "Search..." %></li>
                
                <li><%= f.submit({:class=>"btn btn-outline-dark", value: "Enter"}) %></li>
              </ul>
            
              <% end %>
          <% end %>

          

          <% if user_signed_in? %>
          <div class="dropdown text-end">
            <div class="d-block link-dark text-decoration-none dropdown-toggle" type="button" id="dropdownUser1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              
              <% if User.find(current_user.id).image.attached? %>
                  <%= image_tag User.find(current_user.id).image, :class=>"rounded-circle smallAvatar" %>
                <% else %>
                  <%= image_tag "https://cdn.icon-icons.com/icons2/1378/PNG/512/avatardefault_92824.png", :class=>"rounded-circle smallAvatar" %>
                <% end %>
            </div>
            <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
              <li><%= link_to "Create post", new_post_path, class: "link-item dropdown-item" %></li>
              <li><%= link_to "Profile", profile_path, class: "link-item dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "link-item dropdown-item" %></li>
            </ul>
          </div>
          <% else %>

          <div class="dropdown text-end">
            <div class="d-block link-dark text-decoration-none dropdown-toggle" type="button" id="dropdownUser1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <img src="https://cdn.icon-icons.com/icons2/1378/PNG/512/avatardefault_92824.png" alt="mdo" width="32" height="32" class="rounded-circle">
            </div>
            <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
              <li><%= link_to "Log In", new_user_session_path, class: "link-item dropdown-item" %></a></li>
              <li><%= link_to "Registrate", new_user_registration_path, class: "link-item dropdown-item" %></a></li>
            </ul>
          </div>
          <% end %>
        </div>
      </div>
    </header>
 
    <center class="newPost ">
      <% if notice %>
        <p class="notice alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert alert-warning"><%= alert %></p>
      <% end %>
    </center>
    <%= yield %>
    
    

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    
  </body>
</html>

app/views/pages/about.html.erb
<center>
  <h3>About us</h3>
</center>

app/views/pages/account.html.erb
<div class="newPostShow">
<div class="alert alert-dark">
<% if user_signed_in? %>
  <h1>
    <%= User.find(current_user.id).email %>
  </h1>

  <% if User.find(current_user.id).image.attached? %>
    <%= image_tag @User.find(@post.user_id).image, :class=>"postedImage" %>
  <% end %>
  <hr>
  
<% end %>
</div>

app/views/pages/change_user_avatar.html.erb
<div class="newPost">
  <%= form_for :avatar, url: change_user_avatar_method_path do |f| %>
  
    <h3>Change avatar</h3>
    
    <p>
      Choose avatar <br>
      <%= f.file_field :image, class: "form-control"%>
    </p>

    <p>
      <%= f.submit({:class=>"btn btn-success"}) %>
    </p>


  <% end %>
</div>

app/views/pages/contacts.html.erb
<center>
  <h3>Contacts</h3>
</center>

app/views/pages/curruserposts.html.erb
<div class="row postsTable">
<% if user_signed_in? %>

    

    <div class="col-sm">
      <p>
      <h2><%= current_user.email %></h2> 
        <% if User.find(current_user.id).image.attached? %>
        
            <%= link_to change_user_avatar_path do %>
              <%= image_tag User.find(current_user.id).image, :class=>"rounded-circle avatar" %>
            <% end %>

        <% else %>
          <%= link_to change_user_avatar_path do %>
            <%= image_tag "https://cdn.icon-icons.com/icons2/1378/PNG/512/avatardefault_92824.png", :class=>"rounded-circle avatar" %>
            <i>Click to choose avatar</i>
          <% end %>
        <% end %>

        
      </p><p></p><br>
      <% if @posts.empty? %>
        <p class="text text-danger">You haven't created any post yet!</p>
      <% else %>

      <h3>Your posts</h3>
      <hr>
      <% @posts.each do |post| %>
        <h4> <%= post.title %></h4>
        <p><%= post.body %></p>
        <%= link_to "More...", post_path(post), :class=>"btn btn-outline-dark" %>
        <hr>
        <% end %>
      <% end %>

      
      

    </div>

<% end %>
</div>

app/views/posts/edit.html.erb
<div class="newPost">
  <%= form_for :post, url: post_path(@post),method: :patch do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%=msg %></div>
    <% end %>
  <% end %>
    <h3>Edit post</h3>
    <p>
      Name <br>
      <%= f.text_field(:title, {:class=>"form-control"}) %>
    </p>
    <p>
      Content <br>
      <%= f.text_area(:body,{:class=>"form-control"}) %>
    </p>

    <p>
      <%= f.submit({:class=>"btn btn-success"}) %>
    </p>
  <% end %>
</div>

app/views/posts/index.html.erb
    <center>

      <h1>Main Page</h1>
    </center>

    <div class="row postsTable">

        <div class="col-sm">
          <h3>Recent posts</h3>
          <hr>
          <% @posts.each do |post| %>
            <h4> <%= post.title %></h4>
            <p><%= post.body %></p>
            <%= link_to "More...", post_path(post), :class=>"btn btn-outline-dark" %>
            <hr>
          <% end %>
        </div>

      <div class="col-sm-3 alert alert-dark">
        <h3>Popular posts</h3>
        <ul>
          <% @topPosts.each do |post| %>
            <br>
            <br>
            <li><h4><%= link_to post.title, post_path(post), :class=>"text text-dark" %></h4>
              <span align="left">
                <i>Comments: <%= post.comments.count %></i>
              </span>
            </li>

          <% end %>
          
        </ul>
      </div>


    </div>

app/views/posts/new.html.erb
<div class="newPost">
  <%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%=msg %></div>
    <% end %>
  <% end %>
    <h3>Create post</h3>
    <p>
      Name <br>
      <%= f.text_field(:title, {:class=>"form-control"}) %>
    </p>
    <p>
      Content <br>
      <%= f.text_area(:body,{:class=>"form-control"}) %>
    </p>

    <p>
      Image <br>
      <%= f.file_field :image, class: "form-control"%>
    </p>

    <p>
      <%= f.submit({:class=>"btn btn-success"}) %>
    </p>


  <% end %>
</div>

app/views/posts/search.html.erb
    <center>

    <h1>Search results</h1>
  </center>

  <div class="row postsTable">

      <div class="col-sm">

        <% @posts.each do |post| %>
          <h4> <%= post.title %></h4>
          <p><%= post.body %></p>
          <%= link_to "More...", post_path(post), :class=>"btn btn-outline-dark" %>
          <hr>
        <% end %>
      </div>


  </div>

app/views/posts/show.html.erb
<div class="newPostShow">
<div class="alert alert-dark">
  <p>
    <% if User.find(@post.user_id).image.attached? %>
            <%= image_tag User.find(@post.user_id).image, :class=>"rounded-circle smallAvatar" %>
    <% else %>
            <%= image_tag "https://cdn.icon-icons.com/icons2/1378/PNG/512/avatardefault_92824.png", :class=>"rounded-circle smallAvatar" %>
    <% end %>
    <strong><%= User.find(@post.user_id).email %>:</strong></p>
  <h1>
    <%= @post.title %>
  </h1>
  <p>
    <%= @post.body %>
  </p>
  <% if @post.image.attached? %>
    <%= image_tag @post.image, :class=>"postedImage" %>
  <% end %>
  <hr>
  <% if user_signed_in? %>
    <% if @post.user_id == current_user.id %>
      <%= link_to "Edit", edit_post_path(@post), :class=>"btn btn-warning" %>
      <br><br>
      <%= button_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, :class=>"btn btn-danger" %>
    <% end %>
  <% end %>


    <br><br>
    <% if @post.comments.empty? %>
      <p class="text text-danger">There are no comments yet</p>
    <% else %>
      <h4><i>Recent comments</i></h4>
      <% @post.comments.each do |comment| %>
      <hr>
        <p>
          <strong> <%= comment.userName %>:</strong>
          <%= comment.body %>
        </p>
    <% end %>
  <% end %>
  </div>
<% if user_signed_in? %>
  <%= form_for([@post, @post.comments.build]) do |f| %>
    <h3>Your comment:</h3>

    <p>
      <%= f.text_area(:body,{:class=>"form-control"}) %>
    </p>

    <p>
      <%= f.submit("Comment",{:class=>"btn btn-success"}) %>
    </p>
  <% end %>
<% end %>
<br><br><br>
</div>